name: Build and Deploy to Cloud Run

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: swdevprac
  REGION: asia-southeast1
  SERVICE: gogotalkie
  REPO: cloud-run-source-deploy
  WORKLOAD_IDENTITY_PROVIDER: projects/898222558375/locations/global/workloadIdentityPools/github-actions/providers/github
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v3'
        with:
          project_id : '${{env.PROJECT_ID}}'
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'

      - name: Configure Docker to use Artifact Registry
        run: gcloud auth configure-docker ${env.REGION}-docker.pkg.dev

      - name: Build and Push Container
        env:
          IMAGE: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.SERVICE }}:${{ github.sha }}
        run: |
          echo "IMAGE=${IMAGE}"
          docker build --tag "${IMAGE}" .
          docker push "${IMAGE}"
          echo "IMAGE=${IMAGE}" >> "$GITHUB_ENV"

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.SERVICE }}:${{ github.sha }}

      - name: Show output
        run: echo ${{ steps.deploy.outputs.url }}
