name: Build and Deploy to Cloud Run

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

env:
  PROJECT_ID: swdevprac
  REGION: asia-southeast1
  SERVICE: gogotalkie
  REPO: cloud-run-source-deploy
  WORKLOAD_IDENTITY_PROVIDER: projects/898222558375/locations/global/workloadIdentityPools/github-actions/providers/github
  SERVICE_ACCOUNT_EMAIL: 898222558375-compute@developer.gserviceaccount.com 

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT_EMAIL }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build & Push
        env:
          IMAGE: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.SERVICE }}:${{ github.sha }}
        run: |
          echo "IMAGE=${IMAGE}"
          docker build -t "${IMAGE}" .
          docker push "${IMAGE}"
          echo "IMAGE=${IMAGE}" >> "$GITHUB_ENV"

      - id: deploy
        name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.IMAGE }}
          flags: --port=8080 --allow-unauthenticated
